SERVICE:
    SERVICE_IP: "0.0.0.0"
    SERVICE_PORT: 5000
    LOG_PATH: "logfile"

    # class
    CLASS_PATH: "model/Class.txt"

    # Model B7
    MODEL_PATH: "model/checkpoint-4.pth.tar"
    NUMBER_CLASS: 8
    BATCH_SIZE: 8

    # folder data
    DATA_CK_DIR: "data_ck"
    PATH_DATA_CK: "path_data_ck"